# Generated by Django 2.2.5 on 2020-02-28 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='cargo',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='servico',
            new_name='nome',
        ),
    ]
